# Generated by Django 3.0 on 2020-01-17 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doctorname', models.CharField(max_length=100)),
                ('doctorqualification', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_desc', models.CharField(max_length=200)),
                ('product_price', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(default=datetime.date.today)),
                ('deleteFlag', models.BooleanField(default=0)),
            ],
        ),
    ]
