# Generated by Django 3.0 on 2020-01-20 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthAdmin', '0003_auto_20200119_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=30)),
                ('addDate', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
