# Generated by Django 3.0 on 2020-01-20 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthAdmin', '0004_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.IntegerField(default=0)),
                ('disease', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
