# Generated by Django 3.0 on 2020-01-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthAdmin', '0005_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='cure',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='precautions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(),
        ),
    ]
