# Generated by Django 3.0 on 2020-01-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthAdmin', '0006_auto_20200127_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='clinicID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinicID',
            field=models.IntegerField(default=0),
        ),
    ]
